-- MySQL Script generated by MySQL Workbench
-- Пт 25 янв 2019 19:23:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sk_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sk_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sk_project` DEFAULT CHARACTER SET utf8 ;
USE `sk_project` ;

-- -----------------------------------------------------
-- Table `sk_project`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sk_project`.`users` ;

CREATE TABLE IF NOT EXISTS `sk_project`.`users` (
  `idUser` CHAR(64) NOT NULL,
  `username` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `last_enter` DATETIME NULL,
  `ip` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sk_project`.`users_meta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sk_project`.`users_meta` ;

CREATE TABLE IF NOT EXISTS `sk_project`.`users_meta` (
  `idUsers_meta` BIGINT NOT NULL AUTO_INCREMENT,
  `users_idUser` CHAR(64) NOT NULL,
  `key` VARCHAR(45) NOT NULL,
  `value` VARCHAR(450) NULL,
  PRIMARY KEY (`idUsers_meta`, `users_idUser`),
  INDEX `fk_users_meta_users_idx` (`users_idUser` ASC),
  UNIQUE INDEX `idUsers_meta_UNIQUE` (`idUsers_meta` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sk_project`.`contents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sk_project`.`contents` ;

CREATE TABLE IF NOT EXISTS `sk_project`.`contents` (
  `idContent` CHAR(64) NOT NULL,
  `users_idUser` CHAR(64) NOT NULL,
  `type` VARCHAR(45) NULL,
  `title` VARCHAR(255) NULL,
  `sub_title` VARCHAR(255) NULL,
  `description` VARCHAR(512) NULL,
  `content` MEDIUMTEXT NULL,
  PRIMARY KEY (`idContent`, `users_idUser`),
  INDEX `fk_contents_users1_idx` (`users_idUser` ASC),
  UNIQUE INDEX `idContent_UNIQUE` (`idContent` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sk_project`.`contents_meta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sk_project`.`contents_meta` ;

CREATE TABLE IF NOT EXISTS `sk_project`.`contents_meta` (
  `idContents_meta` BIGINT NOT NULL AUTO_INCREMENT,
  `contents_idContent` CHAR(64) NOT NULL,
  `key` VARCHAR(45) NOT NULL,
  `value` VARCHAR(450) NULL,
  PRIMARY KEY (`idContents_meta`, `contents_idContent`),
  INDEX `fk_contents_meta_contents1_idx` (`contents_idContent` ASC),
  UNIQUE INDEX `idContents_meta_UNIQUE` (`idContents_meta` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `sk_project`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `sk_project`;
INSERT INTO `sk_project`.`users` (`idUser`, `username`, `email`, `password`, `type`, `last_enter`, `ip`) VALUES ('0', 'Sergei Kharlamov', 'unanimity@list.ru', 'empty', '0', '2018-06-08 12:39:52', '');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sk_project`.`users_meta`
-- -----------------------------------------------------
START TRANSACTION;
USE `sk_project`;
INSERT INTO `sk_project`.`users_meta` (`idUsers_meta`, `users_idUser`, `key`, `value`) VALUES (DEFAULT, '0', 'img_url', 'www.vk.ru');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sk_project`.`contents`
-- -----------------------------------------------------
START TRANSACTION;
USE `sk_project`;
INSERT INTO `sk_project`.`contents` (`idContent`, `users_idUser`, `type`, `title`, `sub_title`, `description`, `content`) VALUES ('0', '0', 'project', 'Personal site', '-----', 'ji ji jolh jh', 'content ffffcontent ffffcontent ffffcontent ffffcontent ffffcontent ffffcontent ffffcontent ffff');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sk_project`.`contents_meta`
-- -----------------------------------------------------
START TRANSACTION;
USE `sk_project`;
INSERT INTO `sk_project`.`contents_meta` (`idContents_meta`, `contents_idContent`, `key`, `value`) VALUES (DEFAULT, '0', 'likes', '21');

COMMIT;

